### ISSUE TITLE
Generated changelog

### ISSUE THREAD

**Issue by vrtxf** [superleap/react-material-boilerplate#6]
A changelog following [keepachangelog.com](http://keepachangelog.com/) syntax should be implemented and generated via `npm run-script documentation` or similar. 
Currently only working plugin to fetch more than 50 requests via token is [github_changelog_generator](https://skywinder.github.io/github-changelog-generator/)

**Comment by 0-vortex** [comment]
`standard-changelog` from superleap/github-issues-label-sync
